<?xml version="1.0" encoding="utf-8"?>
<body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<LD>
 </LD>
 <addData>
  <data name="docInformation" handleUnknown="preserve">
   <docInformation xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" gridActive="true" pageWidth="-1">
    <version>2.999.999.999.999</version>
    <multilineOptions maximumContactWidth="13" minimumContactWidth="13" maximumContactLines="1" contactEllipse="true" maximumInstanceNameWidth="2147483647" maximumInstanceNameLines="1" instanceNameEllipse="false" maximumVariableWidth="2147483647" variableEllipse="false" />
   </docInformation>
  </data>
 </addData>
</body>
